 {
 Qquit='Voulez-vous continuer ou quitter?'
 Qcontinu='Voulez-vous continuer?'
 Qnew='Nouveau projet ?'
 Qok='Quitter'
 Qcont='Continuer'
 Qwarning='Attention'
 Qalerte='Vous allez supprimer un projet et ses fichiers'
 AlertWinOpen='Vous devez fermer la fenêtre déjà ouverte'
 Annul='Annuler'
 NewProject='Nouveau projet'
 Mfichier='Fichier',
 Mnew='Nouveau projet',
 Mouvrir='Ouvrir un projet',
 Mouvrirc='Ouvrir un cliché',
 Mnewspace='Nouvel espace',
 Msave='Sauvegarder',
 MsaveAs='Sauvegarder sous',
 Mrename='Renommer',
 Mdel='Supprimer',
 Msavegrp='Sauvegarder Groupe',
 Mimportgrp='Importer groupe',
 Mquit='Quiter'
 Medition='Edition'
 Mannuler='Annuler'
 Mretablir='Rétablir'
 Mcouper='Couper'
 Mcopier='Copier'
 Mcoller='Coller'
 MspecialCollage='Collage spécial'
 MsansGrp='Sans les groupes'
 McommeGrp='Comme groupe'
 MtoutSelect='Tout sélectionner'
 Mgrouper='Grouper'
 Mdegrouper='Dégrouper'
 Mregrouper='Regrouper'
 MtoutDegrouper='Tout dégrouper'
 McouleurGrp='Couleur Groupe'
 MformeGrp='Forme Groupe'
 Malign='Alignement'
 MaGauche='À gauche'
 MenHaut='En haut'
 MaDroite='À droite'
 MenBas='En bas'
 Mdeplacement='Déplacement'
 MtoutBas='Tout en bas'
 MversBas='Vers le bas'
 MversHaut='Vers le haut'
 MtoutHaut='Tout en haut'
 Mzoom='Zoom'
 Matelier='Atelier'
 MaugDim='Augm.Dim'
 Mpermut='Permutation'
 Mpalindrome='Palindrome'
 Minclus='Inclusion'
 Mrenv='Renversement'
 Mretro='Rétrograde'
 MrenvRet='Renv.Retrograde'
 Mtempo='Tempo (objet)'
 Mrendus='Rendus'
 Mimgsvg='Image svg'
 Mgrpsvg='Vue groupe svg'
 Mpartsvg='Partition svg'
 Mobjetwav='Objet (wav)'
 Mgrpwav='Groupe (wav)'
 Mintervwav='Intervalle (wav)'
 Mpistewav='Piste (wav)'
 Mpartwav='Partition (wav)'
 MobjActif='Export Objet Actif'
 Moutils='Outils'
 Mlisteaudios='Liste audios'
 MexportObj='Export.Objet'
 MexportGrp='Export.Groupe'
 MexportInterv='Export.Intervalle'
 MexportPart='Export.Partition'
 Mconfig='Configuration'
 Mdoc='Documentation'
 Mhelp='Aide'
 Mwindow='Fenêtre'
 MscaleGrp="Échelle"
 MsaveTheme="Sauv. Theme"
 MloadTheme="Select.Theme"
 Mexport="Exporter"
 Mprefs="Préférences"
 Mwaveform="Forme d'onde"
 Mstudio="Nouveau studio"
 MStdLoad="Ouvrir un studio"
 MStdSave="Enregistrer un studio"
 MIde="IDE Faust"
 }
