function generateSpatDSP(layout, numInputs) {
    if (!layout || !layout.speakers) throw new Error("Layout invalide");

    const speakers = layout.speakers;
    const numSpeakers = speakers.length;

    // Génère les tables Faust pour les coordonnées et distances
    const makeTable = (field) =>
        speakers
            .map((sp, i) => `tabSpeaker${field.charAt(0).toUpperCase() + field.slice(1)}(${i}) = ${sp[field]};`)
            .join("\n");

    // Code Faust généré
    const dspCode = `
declare name        "${layout.name || 'Spat Object'}";
declare version     "1.0";
declare author      "AutoGenerated";
declare license     "BSD";

import("stdfaust.lib");

// === TABLES ===
${makeTable("x")}
${makeTable("y")}
${makeTable("z")}
${makeTable("d")}
Matrix(N,M) =_<: par(out, M, *(Fader(1,out): si.smoo)) :> par(out, M, _)
with {
// === SLIDERS OBJET ===
dtencGen(in, out) = sqrt(pow(tabSpeakerX(out)-x(in),2) + pow(tabSpeakerY(out)+y(in),2) + pow(tabSpeakerZ(out)-z(in),2));
hspot = hslider("Hot Spot",-20,-50,0,1);
dgain(in, out) = ba.db2linear((hspot/tabSpeakerD(out))*dtencGen(in,out));
x(i) = hslider("/X%i",0,-1,1,0.01);
y(i) = hslider("/Y%i",0,-1,1,0.01);
z(i) = hslider("/Z%i",0,-1,1,0.01);
Fader(in,out)= vgroup("[1]Input %2in",dgain(in,out)*cdistance);
cdistance(in)=hslider("dt",1,0,1,0.1):si.smoo;
paramDistance(x)=hgroup("[2]Distance",x);
};
process =par(j,${numInputs},_):>Matrix(1,${numSpeakers});
`;
console.log("dsp",dspCode);
    return dspCode;
}

/*
Explications

N → nombre de canaux de l'objet audio.

M → nombre de sorties du layout (ici 18).

tabSpeakerX/Y/Z/D → positions et distance des speakers.

Matrix(N,M) → génère la matrix N→M.

Fader(in,out) → calcule le gain de chaque speaker selon distance et hot spot.

Les sliders /X%i /Y%i /Z%i permettront de piloter la trajectoire 3D par spline via le code JS.

*/

async function compileSpatDSP(dspSource, dspName = "spat") {
    const faustPkg = await import("./node_modules/@grame/faustwasm/dist/esm/index.js");
    const { instantiateFaustModuleFromFile, LibFaust, FaustCompiler, FaustMonoDspGenerator, FaustMonoOfflineProcessor } = faustPkg;

    const faustModule = await instantiateFaustModuleFromFile(
        "./node_modules/@grame/faustwasm/libfaust-wasm/libfaust-wasm.js"
    );
    const libFaust = new LibFaust(faustModule);
    const compiler = new FaustCompiler(libFaust);

    const gen = new FaustMonoDspGenerator();
    // Compilation → renvoie le WASM compilé
    const wasm = await gen.compile(compiler, dspName, dspSource, "");

    return {
        wasm,   // juste le WASM compilé
        createProcessor(sampleRate = 48000, blockSize = 1024) {
            // IMPORTANT : on passe directement le WASM à l'OfflineProcessor
            return new FaustMonoOfflineProcessor(wasm, sampleRate, blockSize);
        }
    };
}


async function loadSpatializer(layoutName) {
    // 1) Génère DSP source
    
    const layoutJSON = await loadLayoutJSON(spat3D); // spat3D = nom du layout
    const M = layoutJSON.speakers.length;
    const dspSource = await generateSpatDSP(M,layoutJSON);
console.log("dspSource",dspSource);
    // 2) Compile DSP → WASM
    const wasm = await compileSpatDSP(dspSource, "spat");

    console.log("Spatializer ready:", wasm);

    return wasm; // json, wasm, factory
}


async function createSpatializersForObjects(layoutName) {
	
    // 1) Génère le DSP une fois
    const dspSource = await generateSpatDSP(layoutName);
    console.log("dspSource",dspSource);

    // 2) Compile le DSP
    const wasmFactory = await compileSpatDSP(dspSource, "spat");
	 console.log("wasmFactory",wasmFactory);
    // 3) Crée une instance WASM par objet
    
    const spatializers = tableObjet.map(obj => {
    	(async () => {
        let gen = new wasmFactory.constructor(); // ou selon l'API faustwasm
        gen = await wasmFactory.createOfflineProcessor(48000, 1024);; // init avec sampleRate
        console.log("spatializers",gen);
        return gen;
   })();

});
 
    return spatializers; // tableau d'instances indépendantes

}

// ══════════════════════════════════════════════════════════
//  HOA — Higher Order Ambisonics (ACN/SN3D)
// ══════════════════════════════════════════════════════════

/**
 * Calcule les harmoniques sphériques réelles ACN/SN3D jusqu'à l'ordre N
 * pour une position (az, el) en radians.
 * Convention : x = cosAz*cosEl (avant), y = sinAz*cosEl (gauche), z = sinEl (haut)
 */
function computeSH(order, az, el) {
    const cosAz = Math.cos(az), sinAz = Math.sin(az);
    const cosEl = Math.cos(el), sinEl = Math.sin(el);
    const x = cosAz * cosEl;
    const y = sinAz * cosEl;
    const z = sinEl;

    const c = [1.0]; // ACN 0
    if (order >= 1) {
        c.push(
            1.7320508  * y,          // ACN 1  √3 y
            1.7320508  * z,          // ACN 2  √3 z
            1.7320508  * x           // ACN 3  √3 x
        );
    }
    if (order >= 2) {
        c.push(
            3.8729833  * x * y,                      // ACN 4  √15 xy
            3.8729833  * y * z,                      // ACN 5  √15 yz
            1.1180340  * (3*z*z - 1),                // ACN 6  √5/2 (3z²-1)
            3.8729833  * x * z,                      // ACN 7  √15 xz
            1.9364917  * (x*x - y*y)                 // ACN 8  √15/2 (x²-y²)
        );
    }
    if (order >= 3) {
        c.push(
            2.0916501  * y * (3*x*x - y*y),          // ACN 9
            10.2469762 * x * y * z,                  // ACN 10
            1.6201852  * y * (4*z*z - x*x - y*y),   // ACN 11
            1.3228757  * z * (2*z*z - 3*(x*x+y*y)), // ACN 12
            1.6201852  * x * (4*z*z - x*x - y*y),   // ACN 13
            5.1234754  * (x*x - y*y) * z,            // ACN 14
            2.0916501  * x * (x*x - 3*y*y)           // ACN 15
        );
    }
    if (order >= 4) {
        c.push(
            2.5033429  * x * y * (x*x - y*y),
            1.7701307  * y * z * (3*x*x - y*y),
            0.9461747  * x * y * (7*z*z - 1),
            0.6690466  * y * z * (7*z*z - 3),
            0.1057855  * (35*z*z*z*z - 30*z*z + 3),
            0.6690466  * x * z * (7*z*z - 3),
            0.4730874  * (x*x - y*y) * (7*z*z - 1),
            1.7701307  * x * z * (x*x - 3*y*y),
            0.6258357  * (x*x*x*x - 6*x*x*y*y + y*y*y*y)
        );
    }
    if (order >= 5) {
        c.push(
            0.6563820  * y * (5*x*x*x*x - 10*x*x*y*y + y*y*y*y),
            8.3026942  * x * y * z * (x*x - y*y),
            0.4892382  * y * (3*x*x - y*y) * (9*z*z - 1),
            4.7935688  * x * y * z * (3*z*z - 1),
            0.4528672  * y * (21*z*z*z*z - 14*z*z + 1),
            0.1169503  * z * (63*z*z*z*z - 70*z*z + 15),
            0.4528672  * x * (21*z*z*z*z - 14*z*z + 1),
            2.3967844  * (x*x - y*y) * z * (3*z*z - 1),
            0.4892382  * x * (x*x - 3*y*y) * (9*z*z - 1),
            2.0756736  * (x*x*x*x - 6*x*x*y*y + y*y*y*y) * z,
            0.6563820  * x * (x*x*x*x - 10*x*x*y*y + 5*y*y*y*y)
        );
    }
    if (order >= 6) {
        c.push(
            1.3663682  * x * y * (3*x*x*x*x - 10*x*x*y*y + 3*y*y*y*y),
            2.3666191  * y * z * (5*x*x*x*x - 10*x*x*y*y + y*y*y*y),
            2.0182596  * x * y * (x*x - y*y) * (11*z*z - 1),
            0.9212052  * y * z * (3*x*x - y*y) * (11*z*z - 3),
            0.9212052  * x * y * (11*z*z*z*z - 6*z*z + 0.333333),
            0.5826070  * y * z * (33*z*z*z*z - 30*z*z + 5),
            0.0635693  * (231*z*z*z*z*z*z - 315*z*z*z*z + 105*z*z - 5),
            0.5826070  * x * z * (33*z*z*z*z - 30*z*z + 5),
            0.4606026  * (x*x - y*y) * (11*z*z*z*z - 6*z*z + 0.333333),
            0.9212052  * x * z * (x*x - 3*y*y) * (11*z*z - 3),
            0.5045649  * (x*x*x*x - 6*x*x*y*y + y*y*y*y) * (11*z*z - 1),
            2.3666191  * x * z * (x*x*x*x - 10*x*x*y*y + 5*y*y*y*y),
            0.6831841  * (x*x*x*x*x*x - 15*x*x*x*x*y*y + 15*x*x*y*y*y*y - y*y*y*y*y*y)
        );
    }
    if (order >= 7) {
        c.push(
            0.7071068  * y * (7*x*x*x*x*x*x - 35*x*x*x*x*y*y + 21*x*x*y*y*y*y - y*y*y*y*y*y),
            6.0827625  * x * y * z * (3*x*x*x*x - 10*x*x*y*y + 3*y*y*y*y),
            0.7284313  * y * z * (5*x*x*x*x - 10*x*x*y*y + y*y*y*y) * (13*z*z - 1),
            2.9026960  * x * y * (x*x - y*y) * z * (13*z*z - 3),
            0.6472598  * y * (3*x*x - y*y) * (13*z*z*z*z - 6*z*z + 0.2),
            1.0182337  * x * y * z * (13*z*z*z*z - 10*z*z + 1),
            0.5641896  * y * z * (429*z*z*z*z*z*z - 495*z*z*z*z + 135*z*z - 5) * 0.125,
            0.0449435  * (429*z*z*z*z*z*z*z - 693*z*z*z*z*z + 315*z*z*z - 35*z),
            0.5641896  * x * z * (429*z*z*z*z*z*z - 495*z*z*z*z + 135*z*z - 5) * 0.125,
            0.5091169  * (x*x - y*y) * z * (13*z*z*z*z - 10*z*z + 1),
            0.6472598  * x * (x*x - 3*y*y) * (13*z*z*z*z - 6*z*z + 0.2),
            0.7256740  * (x*x*x*x - 6*x*x*y*y + y*y*y*y) * z * (13*z*z - 3),
            0.7284313  * x * z * (x*x*x*x - 10*x*x*y*y + 5*y*y*y*y) * (13*z*z - 1),
            3.0413813  * (x*x*x*x*x*x - 15*x*x*x*x*y*y + 15*x*x*y*y*y*y - y*y*y*y*y*y) * z,
            0.7071068  * x * (x*x*x*x*x*x - 21*x*x*x*x*y*y + 35*x*x*y*y*y*y - 7*y*y*y*y*y*y)
        );
    }
    return c;
}

/**
 * Génère le DSP Faust d'encodage HOA (1 entrée mono → nHoa canaux B-format)
 * Les sliders /X /Y /Z pilotent la position source (coordonnées normalisées [-1,1])
 * comme dans le VBAP existant.
 */
function generateHoaEncoderDSP(order) {
    const nHoa = (order + 1) * (order + 1);

    // Les SH sont exprimées via x,y,z = composantes cartésiennes du vecteur source normalisé
    // On déduit az/el depuis les sliders X,Y,Z : az = atan2(X,Y), el = atan2(Z, sqrt(X²+Y²))
    const shDefs = [
        // ordre 0
        `sh0  = 1.0;`
    ];
    if (order >= 1) {
        shDefs.push(
            `sh1  = 1.7320508  * vy;`,
            `sh2  = 1.7320508  * vz;`,
            `sh3  = 1.7320508  * vx;`
        );
    }
    if (order >= 2) {
        shDefs.push(
            `sh4  = 3.8729833  * vx * vy;`,
            `sh5  = 3.8729833  * vy * vz;`,
            `sh6  = 1.1180340  * (3.0*vz*vz - 1.0);`,
            `sh7  = 3.8729833  * vx * vz;`,
            `sh8  = 1.9364917  * (vx*vx - vy*vy);`
        );
    }
    if (order >= 3) {
        shDefs.push(
            `sh9  = 2.0916501  * vy * (3.0*vx*vx - vy*vy);`,
            `sh10 = 10.2469762 * vx * vy * vz;`,
            `sh11 = 1.6201852  * vy * (4.0*vz*vz - vx*vx - vy*vy);`,
            `sh12 = 1.3228757  * vz * (2.0*vz*vz - 3.0*(vx*vx + vy*vy));`,
            `sh13 = 1.6201852  * vx * (4.0*vz*vz - vx*vx - vy*vy);`,
            `sh14 = 5.1234754  * (vx*vx - vy*vy) * vz;`,
            `sh15 = 2.0916501  * vx * (vx*vx - 3.0*vy*vy);`
        );
    }
    if (order >= 4) {
        shDefs.push(
            `sh16 = 2.5033429  * vx * vy * (vx*vx - vy*vy);`,
            `sh17 = 1.7701307  * vy * vz * (3.0*vx*vx - vy*vy);`,
            `sh18 = 0.9461747  * vx * vy * (7.0*vz*vz - 1.0);`,
            `sh19 = 0.6690466  * vy * vz * (7.0*vz*vz - 3.0);`,
            `sh20 = 0.1057855  * (35.0*vz*vz*vz*vz - 30.0*vz*vz + 3.0);`,
            `sh21 = 0.6690466  * vx * vz * (7.0*vz*vz - 3.0);`,
            `sh22 = 0.4730874  * (vx*vx - vy*vy) * (7.0*vz*vz - 1.0);`,
            `sh23 = 1.7701307  * vx * vz * (vx*vx - 3.0*vy*vy);`,
            `sh24 = 0.6258357  * (vx*vx*vx*vx - 6.0*vx*vx*vy*vy + vy*vy*vy*vy);`
        );
    }
    if (order >= 5) {
        shDefs.push(
            `sh25 = 0.6563820  * vy * (5.0*vx*vx*vx*vx - 10.0*vx*vx*vy*vy + vy*vy*vy*vy);`,
            `sh26 = 8.3026942  * vx * vy * vz * (vx*vx - vy*vy);`,
            `sh27 = 0.4892382  * vy * (3.0*vx*vx - vy*vy) * (9.0*vz*vz - 1.0);`,
            `sh28 = 4.7935688  * vx * vy * vz * (3.0*vz*vz - 1.0);`,
            `sh29 = 0.4528672  * vy * (21.0*vz*vz*vz*vz - 14.0*vz*vz + 1.0);`,
            `sh30 = 0.1169503  * vz * (63.0*vz*vz*vz*vz - 70.0*vz*vz + 15.0);`,
            `sh31 = 0.4528672  * vx * (21.0*vz*vz*vz*vz - 14.0*vz*vz + 1.0);`,
            `sh32 = 2.3967844  * (vx*vx - vy*vy) * vz * (3.0*vz*vz - 1.0);`,
            `sh33 = 0.4892382  * vx * (vx*vx - 3.0*vy*vy) * (9.0*vz*vz - 1.0);`,
            `sh34 = 2.0756736  * (vx*vx*vx*vx - 6.0*vx*vx*vy*vy + vy*vy*vy*vy) * vz;`,
            `sh35 = 0.6563820  * vx * (vx*vx*vx*vx - 10.0*vx*vx*vy*vy + 5.0*vy*vy*vy*vy);`
        );
    }
    if (order >= 6) {
        shDefs.push(
            `sh36 = 1.3663682  * vx * vy * (3.0*vx*vx*vx*vx - 10.0*vx*vx*vy*vy + 3.0*vy*vy*vy*vy);`,
            `sh37 = 2.3666191  * vy * vz * (5.0*vx*vx*vx*vx - 10.0*vx*vx*vy*vy + vy*vy*vy*vy);`,
            `sh38 = 2.0182596  * vx * vy * (vx*vx - vy*vy) * (11.0*vz*vz - 1.0);`,
            `sh39 = 0.9212052  * vy * vz * (3.0*vx*vx - vy*vy) * (11.0*vz*vz - 3.0);`,
            `sh40 = 0.9212052  * vx * vy * (11.0*vz*vz*vz*vz - 6.0*vz*vz + 0.333333);`,
            `sh41 = 0.5826070  * vy * vz * (33.0*vz*vz*vz*vz - 30.0*vz*vz + 5.0);`,
            `sh42 = 0.0635693  * (231.0*vz*vz*vz*vz*vz*vz - 315.0*vz*vz*vz*vz + 105.0*vz*vz - 5.0);`,
            `sh43 = 0.5826070  * vx * vz * (33.0*vz*vz*vz*vz - 30.0*vz*vz + 5.0);`,
            `sh44 = 0.4606026  * (vx*vx - vy*vy) * (11.0*vz*vz*vz*vz - 6.0*vz*vz + 0.333333);`,
            `sh45 = 0.9212052  * vx * vz * (vx*vx - 3.0*vy*vy) * (11.0*vz*vz - 3.0);`,
            `sh46 = 0.5045649  * (vx*vx*vx*vx - 6.0*vx*vx*vy*vy + vy*vy*vy*vy) * (11.0*vz*vz - 1.0);`,
            `sh47 = 2.3666191  * vx * vz * (vx*vx*vx*vx - 10.0*vx*vx*vy*vy + 5.0*vy*vy*vy*vy);`,
            `sh48 = 0.6831841  * (vx*vx*vx*vx*vx*vx - 15.0*vx*vx*vx*vx*vy*vy + 15.0*vx*vx*vy*vy*vy*vy - vy*vy*vy*vy*vy*vy);`
        );
    }
    if (order >= 7) {
        shDefs.push(
            `sh49 = 0.7071068  * vy * (7.0*vx*vx*vx*vx*vx*vx - 35.0*vx*vx*vx*vx*vy*vy + 21.0*vx*vx*vy*vy*vy*vy - vy*vy*vy*vy*vy*vy);`,
            `sh50 = 6.0827625  * vx * vy * vz * (3.0*vx*vx*vx*vx - 10.0*vx*vx*vy*vy + 3.0*vy*vy*vy*vy);`,
            `sh51 = 0.7284313  * vy * vz * (5.0*vx*vx*vx*vx - 10.0*vx*vx*vy*vy + vy*vy*vy*vy) * (13.0*vz*vz - 1.0);`,
            `sh52 = 2.9026960  * vx * vy * (vx*vx - vy*vy) * vz * (13.0*vz*vz - 3.0);`,
            `sh53 = 0.6472598  * vy * (3.0*vx*vx - vy*vy) * (13.0*vz*vz*vz*vz - 6.0*vz*vz + 0.2);`,
            `sh54 = 1.0182337  * vx * vy * vz * (13.0*vz*vz*vz*vz - 10.0*vz*vz + 1.0);`,
            `sh55 = 0.5641896  * vy * vz * (429.0*vz*vz*vz*vz*vz*vz - 495.0*vz*vz*vz*vz + 135.0*vz*vz - 5.0) * 0.125;`,
            `sh56 = 0.0449435  * (429.0*vz*vz*vz*vz*vz*vz*vz - 693.0*vz*vz*vz*vz*vz + 315.0*vz*vz*vz - 35.0*vz);`,
            `sh57 = 0.5641896  * vx * vz * (429.0*vz*vz*vz*vz*vz*vz - 495.0*vz*vz*vz*vz + 135.0*vz*vz - 5.0) * 0.125;`,
            `sh58 = 0.5091169  * (vx*vx - vy*vy) * vz * (13.0*vz*vz*vz*vz - 10.0*vz*vz + 1.0);`,
            `sh59 = 0.6472598  * vx * (vx*vx - 3.0*vy*vy) * (13.0*vz*vz*vz*vz - 6.0*vz*vz + 0.2);`,
            `sh60 = 0.7256740  * (vx*vx*vx*vx - 6.0*vx*vx*vy*vy + vy*vy*vy*vy) * vz * (13.0*vz*vz - 3.0);`,
            `sh61 = 0.7284313  * vx * vz * (vx*vx*vx*vx - 10.0*vx*vx*vy*vy + 5.0*vy*vy*vy*vy) * (13.0*vz*vz - 1.0);`,
            `sh62 = 3.0413813  * (vx*vx*vx*vx*vx*vx - 15.0*vx*vx*vx*vx*vy*vy + 15.0*vx*vx*vy*vy*vy*vy - vy*vy*vy*vy*vy*vy) * vz;`,
            `sh63 = 0.7071068  * vx * (vx*vx*vx*vx*vx*vx - 21.0*vx*vx*vx*vx*vy*vy + 35.0*vx*vx*vy*vy*vy*vy - 7.0*vy*vy*vy*vy*vy*vy);`
        );
    }

    const channels = Array.from({ length: nHoa }, (_, i) => `*(sh${i})`).join(', ');

    return `
declare name "HOA Encoder Ord${order}";
declare version "1.0";
import("stdfaust.lib");

// Position source (coordonnées cartésiennes normalisées)
rawX = hslider("/X", 0, -1, 1, 0.001) : si.smoo;
rawY = hslider("/Y", 0, -1, 1, 0.001) : si.smoo;
rawZ = hslider("/Z", 0, -1, 1, 0.001) : si.smoo;
gain = hslider("/Gain", 1, 0, 2, 0.001) : si.smoo;

// Normalisation sur sphère unité
len = sqrt(rawX*rawX + rawY*rawY + rawZ*rawZ + 0.0001);
vx = rawX / len;
vy = rawY / len;
vz = rawZ / len;

// Harmoniques sphériques ACN/SN3D
${shDefs.join("\n")}

process = *(gain) <: (${channels});
`;
}

/**
 * Génère le DSP Faust de décodage HOA → enceintes (SAD / pseudo-inverse)
 * Utilise les positions x,y,z du layout JSON pour calculer les coefficients.
 */
function generateHoaDecoderDSP(layout, order) {
    const N  = order;
    const nHoa = (N + 1) * (N + 1);
    const speakers = layout.speakers;
    const P = speakers.length;

    // Calcul de la matrice de décodage (SAD normalisé)
    const D = speakers.map(sp => {
        // Conversion Cartésien → az/el
        const d = Math.sqrt(sp.x*sp.x + sp.y*sp.y + sp.z*sp.z) || 1;
        const nx = sp.x / d, ny = sp.y / d, nz = sp.z / d;
        const az = Math.atan2(nx, ny);          // convention : y=avant, x=droite
        const el = Math.atan2(nz, Math.sqrt(nx*nx + ny*ny));
        return computeSH(N, az, el).map(c => c / P);
    });

    // Génère les constantes Faust
    let decLines = "";
    for (let k = 0; k < P; k++) {
        for (let i = 0; i < nHoa; i++) {
            decLines += `D(${k},${i}) = ${D[k][i].toFixed(8)};\n`;
        }
    }

    return `
declare name "HOA Decoder Ord${N} -> ${P}ch";
declare version "1.0";
import("stdfaust.lib");

${decLines}

speaker(k) = par(i, ${nHoa}, *(D(k,i))) :> _;
process = si.bus(${nHoa}) <: par(k, ${P}, speaker(k));
`;
}
