function generateSpatDSP(layout, numInputs) {
    if (!layout || !layout.speakers) throw new Error("Layout invalide");

    const speakers = layout.speakers;
    const numSpeakers = speakers.length;

    // Génère les tables Faust pour les coordonnées et distances
    const makeTable = (field) =>
        speakers
            .map((sp, i) => `tabSpeaker${field.charAt(0).toUpperCase() + field.slice(1)}(${i}) = ${sp[field]};`)
            .join("\n");

    // Code Faust généré
    const dspCode = `
declare name        "${layout.name || 'Spat Object'}";
declare version     "1.0";
declare author      "AutoGenerated";
declare license     "BSD";

import("stdfaust.lib");

// === TABLES ===
${makeTable("x")}
${makeTable("y")}
${makeTable("z")}
${makeTable("d")}
Matrix(N,M) =_<: par(out, M, *(Fader(1,out): si.smoo)) :> par(out, M, _)
with {
// === SLIDERS OBJET ===
dtencGen(in, out) = sqrt(pow(tabSpeakerX(out)-x(in),2) + pow(tabSpeakerY(out)+y(in),2) + pow(tabSpeakerZ(out)-z(in),2));
hspot = hslider("Hot Spot",-20,-50,0,1);
dgain(in, out) = ba.db2linear((hspot/tabSpeakerD(out))*dtencGen(in,out));
x(i) = hslider("/X%i",0,-1,1,0.01);
y(i) = hslider("/Y%i",0,-1,1,0.01);
z(i) = hslider("/Z%i",0,-1,1,0.01);
Fader(in,out)= vgroup("[1]Input %2in",dgain(in,out)*cdistance);
cdistance(in)=hslider("dt",1,0,1,0.1):si.smoo;
paramDistance(x)=hgroup("[2]Distance",x);
};
process =par(j,${numInputs},_):>Matrix(1,${numSpeakers});
`;
console.log("dsp",dspCode);
    return dspCode;
}

/*
Explications

N → nombre de canaux de l’objet audio.

M → nombre de sorties du layout (ici 18).

tabSpeakerX/Y/Z/D → positions et distance des speakers.

Matrix(N,M) → génère la matrix N→M.

Fader(in,out) → calcule le gain de chaque speaker selon distance et hot spot.

Les sliders /X%i /Y%i /Z%i permettront de piloter la trajectoire 3D par spline via le code JS.

*/

async function compileSpatDSP(dspSource, dspName = "spat") {
    const faustPkg = await import("./node_modules/@grame/faustwasm/dist/esm/index.js");
    const { instantiateFaustModuleFromFile, LibFaust, FaustCompiler, FaustMonoDspGenerator, FaustMonoOfflineProcessor } = faustPkg;

    const faustModule = await instantiateFaustModuleFromFile(
        "./node_modules/@grame/faustwasm/libfaust-wasm/libfaust-wasm.js"
    );
    const libFaust = new LibFaust(faustModule);
    const compiler = new FaustCompiler(libFaust);

    const gen = new FaustMonoDspGenerator();
    // Compilation → renvoie le WASM compilé
    const wasm = await gen.compile(compiler, dspName, dspSource, "");

    return {
        wasm,   // juste le WASM compilé
        createProcessor(sampleRate = 48000, blockSize = 1024) {
            // IMPORTANT : on passe directement le WASM à l'OfflineProcessor
            return new FaustMonoOfflineProcessor(wasm, sampleRate, blockSize);
        }
    };
}


async function loadSpatializer(layoutName) {
    // 1) Génère DSP source
    
    const layoutJSON = await loadLayoutJSON(spat3D); // spat3D = nom du layout
    const M = layoutJSON.speakers.length;
    const dspSource = await generateSpatDSP(M,layoutJSON);
console.log("dspSource",dspSource);
    // 2) Compile DSP → WASM
    const wasm = await compileSpatDSP(dspSource, "spat");

    console.log("Spatializer ready:", wasm);

    return wasm; // json, wasm, factory
}


async function createSpatializersForObjects(layoutName) {
	
    // 1) Génère le DSP une fois
    const dspSource = await generateSpatDSP(layoutName);
    console.log("dspSource",dspSource);

    // 2) Compile le DSP
    const wasmFactory = await compileSpatDSP(dspSource, "spat");
	 console.log("wasmFactory",wasmFactory);
    // 3) Crée une instance WASM par objet
    
    const spatializers = tableObjet.map(obj => {
    	(async () => {
        let gen = new wasmFactory.constructor(); // ou selon l’API faustwasm
        gen = await wasmFactory.createOfflineProcessor(48000, 1024);; // init avec sampleRate
        console.log("spatializers",gen);
        return gen;
   })();

});
 
    return spatializers; // tableau d’instances indépendantes

}

// ══════════════════════════════════════════════════════════
//  HOA — Higher Order Ambisonics (ACN/SN3D)
// ══════════════════════════════════════════════════════════

/**
 * Calcule les harmoniques sphériques réelles ACN/SN3D jusqu’à l’ordre N
 * pour une position (az, el) en radians.
 * Convention : x = cosAz*cosEl (avant), y = sinAz*cosEl (gauche), z = sinEl (haut)
 */
function computeSH(order, az, el) {
    const cosAz = Math.cos(az), sinAz = Math.sin(az);
    const cosEl = Math.cos(el), sinEl = Math.sin(el);
    const x = cosAz * cosEl;
    const y = sinAz * cosEl;
    const z = sinEl;

    const c = [1.0]; // ACN 0
    if (order >= 1) {
        c.push(
            1.7320508  * y,          // ACN 1  √3 y
            1.7320508  * z,          // ACN 2  √3 z
            1.7320508  * x           // ACN 3  √3 x
        );
    }
    if (order >= 2) {
        c.push(
            3.8729833  * x * y,                      // ACN 4  √15 xy
            3.8729833  * y * z,                      // ACN 5  √15 yz
            1.1180340  * (3*z*z - 1),                // ACN 6  √5/2 (3z²-1)
            3.8729833  * x * z,                      // ACN 7  √15 xz
            1.9364917  * (x*x - y*y)                 // ACN 8  √15/2 (x²-y²)
        );
    }
    if (order >= 3) {
        c.push(
            2.0916501  * y * (3*x*x - y*y),          // ACN 9
            10.2469762 * x * y * z,                  // ACN 10
            1.6201852  * y * (4*z*z - x*x - y*y),   // ACN 11
            1.3228757  * z * (2*z*z - 3*(x*x+y*y)), // ACN 12
            1.6201852  * x * (4*z*z - x*x - y*y),   // ACN 13
            5.1234754  * (x*x - y*y) * z,            // ACN 14
            2.0916501  * x * (x*x - 3*y*y)           // ACN 15
        );
    }
    return c;
}

/**
 * Génère le DSP Faust d’encodage HOA (1 entrée mono → nHoa canaux B-format)
 * Les sliders /X /Y /Z pilotent la position source (coordonnées normalisées [-1,1])
 * comme dans le VBAP existant.
 */
function generateHoaEncoderDSP(order) {
    const nHoa = (order + 1) * (order + 1);

    // Les SH sont exprimées via x,y,z = composantes cartésiennes du vecteur source normalisé
    // On déduit az/el depuis les sliders X,Y,Z : az = atan2(X,Y), el = atan2(Z, sqrt(X²+Y²))
    const shDefs = [
        // ordre 0
        `sh0  = 1.0;`
    ];
    if (order >= 1) {
        shDefs.push(
            `sh1  = 1.7320508  * vy;`,
            `sh2  = 1.7320508  * vz;`,
            `sh3  = 1.7320508  * vx;`
        );
    }
    if (order >= 2) {
        shDefs.push(
            `sh4  = 3.8729833  * vx * vy;`,
            `sh5  = 3.8729833  * vy * vz;`,
            `sh6  = 1.1180340  * (3.0*vz*vz - 1.0);`,
            `sh7  = 3.8729833  * vx * vz;`,
            `sh8  = 1.9364917  * (vx*vx - vy*vy);`
        );
    }
    if (order >= 3) {
        shDefs.push(
            `sh9  = 2.0916501  * vy * (3.0*vx*vx - vy*vy);`,
            `sh10 = 10.2469762 * vx * vy * vz;`,
            `sh11 = 1.6201852  * vy * (4.0*vz*vz - vx*vx - vy*vy);`,
            `sh12 = 1.3228757  * vz * (2.0*vz*vz - 3.0*(vx*vx + vy*vy));`,
            `sh13 = 1.6201852  * vx * (4.0*vz*vz - vx*vx - vy*vy);`,
            `sh14 = 5.1234754  * (vx*vx - vy*vy) * vz;`,
            `sh15 = 2.0916501  * vx * (vx*vx - 3.0*vy*vy);`
        );
    }

    const channels = Array.from({ length: nHoa }, (_, i) => `*(sh${i})`).join(‘, ‘);

    return `
declare name "HOA Encoder Ord${order}";
declare version "1.0";
import("stdfaust.lib");

// Position source (coordonnées cartésiennes normalisées)
rawX = hslider("/X", 0, -1, 1, 0.001) : si.smoo;
rawY = hslider("/Y", 0, -1, 1, 0.001) : si.smoo;
rawZ = hslider("/Z", 0, -1, 1, 0.001) : si.smoo;
gain = hslider("/Gain", 1, 0, 2, 0.001) : si.smoo;

// Normalisation sur sphère unité
len = sqrt(rawX*rawX + rawY*rawY + rawZ*rawZ + 0.0001);
vx = rawX / len;
vy = rawY / len;
vz = rawZ / len;

// Harmoniques sphériques ACN/SN3D
${shDefs.join("\n")}

process = *(gain) <: (${channels});
`;
}

/**
 * Génère le DSP Faust de décodage HOA → enceintes (SAD / pseudo-inverse)
 * Utilise les positions x,y,z du layout JSON pour calculer les coefficients.
 */
function generateHoaDecoderDSP(layout, order) {
    const N  = order;
    const nHoa = (N + 1) * (N + 1);
    const speakers = layout.speakers;
    const P = speakers.length;

    // Calcul de la matrice de décodage (SAD normalisé)
    const D = speakers.map(sp => {
        // Conversion Cartésien → az/el
        const d = Math.sqrt(sp.x*sp.x + sp.y*sp.y + sp.z*sp.z) || 1;
        const nx = sp.x / d, ny = sp.y / d, nz = sp.z / d;
        const az = Math.atan2(nx, ny);          // convention : y=avant, x=droite
        const el = Math.atan2(nz, Math.sqrt(nx*nx + ny*ny));
        return computeSH(N, az, el).map(c => c / P);
    });

    // Génère les constantes Faust
    let decLines = "";
    for (let k = 0; k < P; k++) {
        for (let i = 0; i < nHoa; i++) {
            decLines += `D(${k},${i}) = ${D[k][i].toFixed(8)};\n`;
        }
    }

    return `
declare name "HOA Decoder Ord${N} -> ${P}ch";
declare version "1.0";
import("stdfaust.lib");

${decLines}

speaker(k) = par(i, ${nHoa}, *(D(k,i))) :> _;
process = si.bus(${nHoa}) <: par(k, ${P}, speaker(k));
`;
}
