function generateSpatDSP(layout, numInputs) {
    if (!layout || !layout.speakers) throw new Error("Layout invalide");

    const speakers = layout.speakers;
    const numSpeakers = speakers.length;

    // Génère les tables Faust pour les coordonnées et distances
    const makeTable = (field) =>
        speakers
            .map((sp, i) => `tabSpeaker${field.charAt(0).toUpperCase() + field.slice(1)}(${i}) = ${sp[field]};`)
            .join("\n");

    // Code Faust généré
    const dspCode = `
declare name        "${layout.name || 'Spat Object'}";
declare version     "1.0";
declare author      "AutoGenerated";
declare license     "BSD";

import("stdfaust.lib");

// === TABLES ===
${makeTable("x")}
${makeTable("y")}
${makeTable("z")}
${makeTable("d")}
Matrix(N,M) =_<: par(out, M, *(Fader(1,out): si.smoo)) :> par(out, M, _)
with {
// === SLIDERS OBJET ===
dtencGen(in, out) = sqrt(pow(tabSpeakerX(out)-x(in),2) + pow(tabSpeakerY(out)+y(in),2) + pow(tabSpeakerZ(out)-z(in),2));
hspot = hslider("Hot Spot",-20,-50,0,1);
dgain(in, out) = ba.db2linear((hspot/tabSpeakerD(out))*dtencGen(in,out));
x(i) = hslider("/X%i",0,-1,1,0.01);
y(i) = hslider("/Y%i",0,-1,1,0.01);
z(i) = hslider("/Z%i",0,-1,1,0.01);
Fader(in,out)= vgroup("[1]Input %2in",dgain(in,out)*cdistance);
cdistance(in)=hslider("dt",1,0,1,0.1):si.smoo;
paramDistance(x)=hgroup("[2]Distance",x);
};
process =par(j,${numInputs},_):>Matrix(1,${numSpeakers});
`;
console.log("dsp",dspCode);
    return dspCode;
}

/*
Explications

N → nombre de canaux de l’objet audio.

M → nombre de sorties du layout (ici 18).

tabSpeakerX/Y/Z/D → positions et distance des speakers.

Matrix(N,M) → génère la matrix N→M.

Fader(in,out) → calcule le gain de chaque speaker selon distance et hot spot.

Les sliders /X%i /Y%i /Z%i permettront de piloter la trajectoire 3D par spline via le code JS.

*/

async function compileSpatDSP(dspSource, dspName = "spat") {
    const faustPkg = await import("./node_modules/@grame/faustwasm/dist/esm/index.js");
    const { instantiateFaustModuleFromFile, LibFaust, FaustCompiler, FaustMonoDspGenerator, FaustMonoOfflineProcessor } = faustPkg;

    const faustModule = await instantiateFaustModuleFromFile(
        "./node_modules/@grame/faustwasm/libfaust-wasm/libfaust-wasm.js"
    );
    const libFaust = new LibFaust(faustModule);
    const compiler = new FaustCompiler(libFaust);

    const gen = new FaustMonoDspGenerator();
    // Compilation → renvoie le WASM compilé
    const wasm = await gen.compile(compiler, dspName, dspSource, "");

    return {
        wasm,   // juste le WASM compilé
        createProcessor(sampleRate = 48000, blockSize = 1024) {
            // IMPORTANT : on passe directement le WASM à l'OfflineProcessor
            return new FaustMonoOfflineProcessor(wasm, sampleRate, blockSize);
        }
    };
}


async function loadSpatializer(layoutName) {
    // 1) Génère DSP source
    
    const layoutJSON = await loadLayoutJSON(spat3D); // spat3D = nom du layout
    const M = layoutJSON.speakers.length;
    const dspSource = await generateSpatDSP(M,layoutJSON);
console.log("dspSource",dspSource);
    // 2) Compile DSP → WASM
    const wasm = await compileSpatDSP(dspSource, "spat");

    console.log("Spatializer ready:", wasm);

    return wasm; // json, wasm, factory
}


async function createSpatializersForObjects(layoutName) {
	
    // 1) Génère le DSP une fois
    const dspSource = await generateSpatDSP(layoutName);
    console.log("dspSource",dspSource);

    // 2) Compile le DSP
    const wasmFactory = await compileSpatDSP(dspSource, "spat");
	 console.log("wasmFactory",wasmFactory);
    // 3) Crée une instance WASM par objet
    
    const spatializers = tableObjet.map(obj => {
    	(async () => {
        let gen = new wasmFactory.constructor(); // ou selon l’API faustwasm
        gen = await wasmFactory.createOfflineProcessor(48000, 1024);; // init avec sampleRate
        console.log("spatializers",gen);
        return gen;
   })();

});
 
    return spatializers; // tableau d’instances indépendantes
    
}
