async function generateSpatDSP(layoutName) {
    const path = `./Dsp/${layoutName}.json`;
    const raw = await window.api.readFxFile(path);
    const layout = JSON.parse(new TextDecoder().decode(raw));

    const speakers = layout.speakers;
    const P = speakers.length;

    const makeTable = (field) =>
        speakers.map((sp, i) =>
            `tabSpeaker${field}(${i}) = ${sp[field]};`
        ).join("\n");

    const dspCode = `
declare name        "${layout.name}";
declare version     "1.0";
declare author      "AutoGenerated";
declare license     "BSD";
import("stdfaust.lib");

// --- tables ---
${makeTable("x")}
${makeTable("y")}
${makeTable("z")}
${makeTable("d")}

// --- distance ---
dtencGen(in, out) = sqrt(
      pow(tabSpeakerX(out) - x(in), 2)
    + pow(tabSpeakerY(out) - y(in), 2)
    + pow(tabSpeakerZ(out) - z(in), 2)
);

// Hot spot shaping
hspot = hslider("HotSpot", -20, -50, 0, 1);

// gain by distance
dgain(in, out) = ba.db2linear((hspot / tabSpeakerD(out)) * dtencGen(in, out));

// object position controls
x(i) = hslider("/X" + i, 0, -1, 1, 0.01);
y(i) = hslider("/Y" + i, 0, -1, 1, 0.01);
z(i) = hslider("/Z" + i, 0, -1, 1, 0.01);

// distance global control
cdistance(in) = hslider("dt", 1, 0, 1, 0.1) : si.smoo;

// per-output fader
Fader(in, out) = dgain(in, out) * cdistance(in);

// each output = fader of input
out(i) = Fader(1, i);

// --- final process : 1 input → P outputs ---
process = par(i, ${P}, out(i));
`;

    return dspCode;
}



/*
Explications

N → nombre de canaux de l’objet audio.

M → nombre de sorties du layout (ici 18).

tabSpeakerX/Y/Z/D → positions et distance des speakers.

Matrix(N,M) → génère la matrix N→M.

Fader(in,out) → calcule le gain de chaque speaker selon distance et hot spot.

Les sliders /X%i /Y%i /Z%i permettront de piloter la trajectoire 3D par spline via le code JS.

*/

async function compileSpatDSP(dspSource, dspName = "spat") {
    console.log("[Faust] Compilation DSP spat :", dspName);

     const faustPkg = await import("./node_modules/@grame/faustwasm/dist/esm/index.js");
    const { instantiateFaustModuleFromFile, LibFaust, FaustCompiler, FaustMonoDspGenerator } = faustPkg;
    const faustModule = await instantiateFaustModuleFromFile("./node_modules/@grame/faustwasm/libfaust-wasm/libfaust-wasm.js");

    const libFaust = new LibFaust(faustModule);
    const compiler = new FaustCompiler(libFaust);
    const gen = new FaustMonoDspGenerator();

    const res = await gen.compile(compiler, dspName, dspSource, "");

    console.log("[Faust] Compilation OK");

    return {
        generator: gen,
        wasm: res,
        createProcessor: async (sampleRate = 48000, blockSize = 1024) => {
            return await gen.createOfflineProcessor(sampleRate, blockSize);
        }
    };
}



async function loadSpatializer(layoutName) {
    // 1) Génère DSP source
    
    const layoutJSON = await loadLayoutJSON(spat3D); // spat3D = nom du layout
    const M = layoutJSON.speakers.length;
    const dspSource = await generateSpatDSP(M,layoutJSON);
console.log("dspSource",dspSource)
    // 2) Compile DSP → WASM
    const wasm = await compileSpatDSP(dspSource, "spat");

    console.log("Spatializer ready:", wasm);

    return wasm; // json, wasm, factory
}


async function createSpatializersForObjects(layoutName) {
	
    // 1) Génère le DSP une fois
    const dspSource = await generateSpatDSP(layoutName);
    console.log("dspSource",dspSource)

    // 2) Compile le DSP
    const wasmFactory = await compileSpatDSP(dspSource, "spat");
	 console.log("wasmFactory",wasmFactory)
    // 3) Crée une instance WASM par objet
    
    const spatializers = tableObjet.map(obj => {
    	(async () => {
        let gen = new wasmFactory.constructor(); // ou selon l’API faustwasm
        gen = await wasmFactory.createOfflineProcessor(48000, 1024);; // init avec sampleRate
        console.log("spatializers",gen)
        return gen;
   })();

})
 
    return spatializers; // tableau d’instances indépendantes
    
}
