  {
 Qquit='Wollen Sie fortfahren oder aufhören?'
 Qnew='Neues Projekt?'
 Qok='Beenden'
 Qcont='Weitermachen'
 Qwarning='Achtung'
 AlertWinOpen='Sie müssen das bereits geöffnete Fenster schließen'
 Annul='Stornieren'
 NewProject='Neues Projekt'
 Mfichier='Datei',
 Mnew='Neues Projekt',
 Mouvrir='Projekt öffnen',
 Mouvrirc='Schnappschuss öffnen',
 Mnewspace='Neuer Raum',
 Msave='Speichern',
 MsaveAs='Speichern unter',
 Msavegrp='Gruppe speichern',
 Mimportgrp='Gruppe importieren',
 Mquit='Beenden'
 Medition='Bearbeiten'
 Mannuler='Stornieren'
 Mretablir='Wiederherstellen'
 Mcouper='Ausschneiden'
 Mcopier='Kopieren'
 Mcoller='Einfügen'
 MtoutSelect='Alles auswählen'
 Mgrouper='Gruppieren'
 Mdegrouper='Gruppierung aufheben'
 Mregrouper='Regruppieren'
 MtoutDegrouper='Alle Gruppierungen aufheben'
 McouleurGrp='Gruppenfarb'
 MformeGrp='Gruppenform'
 Malign='Ausrichtung'
 MaGauche='Nach links'
 MenHaut='Nach oben'
 MaDroite='Nach rechts'
 MenBas='Nach unten'
 Mdeplacement='Bewegen'
 MtoutBas='Ganz nach unten'
 MversBas='Nach unten'
 MversHaut='Nach oben'
 MtoutHaut='Ganz nach oben'
 Mzoom='Zoom'
 Matelier='Werkstatt'
 MaugDim='Zunahme/Verr.'
 Mpermut='Permutation'
 Mpalindrome='Palindrome'
 Minclus='Einschluss'
 Mrenv='Umkehrung'
 Mretro='Retrograde'
 MrenvRet='Umkeh.Retrograde'
 Mtempo='Tempo (objet)'
 Mrendus='Rendus'
 Mimgsvg='Svg-Bild'
 Mgrpsvg='Gruppenansicht svg'
 Mpartsvg='Partitur svg'
 Mobjetwav='Objekt (wav)'
 Mgrpwav='Gruppe (wav'
 Mintervwav='Intervall (wav)'
 Mpartwav='Partitur (wav)'
 MobjActif='Export Aktives Objekt'
 Moutils='Tools (Werkzeuge)'
 Mlisteaudios='Audioliste'
 MexportObj='Export Objek'
 MexportGrp='Export.Gruppe'
 MexportInterv='Export.Intervall'
 MexportPart='Export.Partitur'
 Mconfig='Konfiguration'
 Mdoc='Dokumentation'
 Mhelp='Hilfe'
 Mwindow='Fenster'
 MscaleGrp="Maßstab"
 MsaveTheme="Thema speichern"
 MloadTheme="Thema wählen"
 Mexport="Exportieren"
 Mprefs="Préférence"
 Mwaveform='Wellenform'
 }
