 {
 Qquit='Do you want to continue or quit?'
 Qnew='New project?'
 Qok='Quit'
 Qcont='Continue'
 Qwarning='Attention'
 AlertWinOpen='You must close the window that is already open'
 Annul='Cancel'
 NewProject='New project'
 Mfichier='File',
 Mnew='New project',
 Mouvrir='Open a project',
 Mouvrirc='Open a snapshot',
 Mnewspace='New space',
 Msave='Save',
 MsaveAs='Save as',
 Msavegrp='Save Group',
 Mimportgrp='Import group',
 Mquit='Quit'
 Medition='Edit'
 Mannuler='Cancel'
 Mretablir='Restore'
 Mcouper='Cut'
 Mcopier='Copy'
 Mcoller='Paste'
 MtoutSelect='Select all'
 Mgrouper='Group'
 Mdegrouper='Ungroup'
 Mregrouper='Regroup'
 MtoutDegrouper='Ungroup all'
 McouleurGrp='Group Colour'
 MformeGrp='Form Groupe'
 Malign='Alignment'
 MaGauche='Left'
 MenHaut='Top'
 MaDroite='Right'
 MenBas='Bottom'
 Mdeplacement='Move'
 MtoutBas='All down'
 MversBas='Down'
 MversHaut='Up'
 MtoutHaut='All Up'
 Mzoom='Zoom'
 Matelier='Workshop'
 MaugDim='Augm.Dim'
 Mpermut='Permutation'
 Mpalindrome='Palindrome'
 Minclus='Inclusion'
 Mrenv='Reversal'
 Mretro='Rétrograd'
 MrenvRet='Rev.Retrograd'
 Mtempo='Tempo (object)'
 Mrendus='Rendus'
 Mimgsvg='Image svg'
 Mgrpsvg='Group view svg'
 Mpartsvg='Partition svg'
 Mobjetwav='Object (wav)'
 Mgrpwav='Group (wav)'
 Mintervwav='Interval (wav)'
 Mpartwav='Partition (wav)'
 MobjActif='Export Active Object'
 Moutils='Preferences'
 Mlisteaudios='Audio list'
 MexportObj='Export.Object'
 MexportGrp='Export.Group'
 MexportInterv='Export.Interval'
 MexportPart='Export.Partition'
 Mconfig='Configuration'
 Mdoc='Documentation'
 Mhelp='Help'
 Mwindow='Window'
 MscaleGrp="Scale"
 MsaveTheme="Sav. Theme"
 MloadTheme="Select.Theme"
 Mexport="Export"
 Mprefs="Preferences"
 Mwaveform="Waveform"
 }
